# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

stages:
  - build

services:
  - docker:dind

# Build production image
build-master:
  stage: build
  script:
    - docker build --pull -t "youngmedia/docker-wordpress" .
    - docker push "youngmedia/docker-wordpress"
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "youngmedia/docker-wordpress:$CI_COMMIT_REF_SLUG" .
    - docker push "youngmedia/docker-wordpress:$CI_COMMIT_REF_SLUG"
  except:
    - master