version: '3.1'
services:
  wordpress:
    build: .
    restart: always
    ports:
      - 8000:80
    environment:
      ROOT_URL: 'http://localhost:8000'
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DEBUG: 1
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3309:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
volumes:
  mysql:
