version: '3.1'
services:
  wordpress:
    build: .
    restart: always
    ports:
      - 8000:80
    environment:
      ROOT_URL: 'http://localhost:8000'
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DEBUG: 1
      REDIS_HOST: redis
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins/
      - ./uploads:/var/www/html/wp-content/uploads/
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3309:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
volumes:
  mysql:
  redis:
