<?php
add_filter('speedmaster__addons', function($addons) {

  $addons[] = array(
    'id' => 'disabled-embed-emojis',
    'title' => __('Remove Emoji/Embed', 'speedmaster'),
    'description' => __('Remove embed and emojis script and css tags generated by WordPress.', 'speedmaster'),
    'file_path' => dirname(__FILE__) . '/disable-embed-emojis.php',
    'vars' => array('SPEEDMASTER__DISABLE_EMBED')
  );

  return $addons;
});